; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\k_sdk\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
